# --------------------------------------------------
# Find first notebook (ignore *_warning.ipynb)
# Create one if none exists
# --------------------------------------------------
find_notebook() {
    NOTEBOOK=$(ls *.ipynb 2>/dev/null | grep -v '_warning.ipynb' | head -n 1)

    if [ -z "$NOTEBOOK" ]; then
        PROJECT_NAME="$(basename "$PWD")"
        NOTEBOOK="${PROJECT_NAME}.ipynb"

        log "📓 No notebook found — creating ${NOTEBOOK}..."

        CREATE_NOTEBOOK_FILE="create_notebook.py"
        write_create_notebook_script "$CREATE_NOTEBOOK_FILE"
        uv run python "$CREATE_NOTEBOOK_FILE" "$PROJECT_NAME" "$NOTEBOOK"
        rm -f "$CREATE_NOTEBOOK_FILE"

        log "✅ Created ${NOTEBOOK}"
    else
        log "📓 First notebook found: $NOTEBOOK"
    fi
}

# --------------------------------------------------
# Register unique kernel
# --------------------------------------------------
register_kernel() {
    KERNEL_NAME="project-$(basename "$PWD")"
    KERNEL_DISPLAY="Python (.venv $(basename "$PWD"))"

    log "📄 Registering kernel: $KERNEL_NAME"

    # If kernel exists, delete it first (stale paths are common)
    if uv run jupyter kernelspec list | grep -q "^$KERNEL_NAME[[:space:]]"; then
        log "♻️ Removing existing kernel: $KERNEL_NAME"
        jupyter kernelspec remove -f "$KERNEL_NAME"
    fi

    # Recreate kernel pointing to current .venv
    uv run python -m ipykernel install \
        --user \
        --name "$KERNEL_NAME" \
        --display-name "$KERNEL_DISPLAY"

    log "✅ Kernel registered: $KERNEL_DISPLAY"
}


# --------------------------------------------------
# Update notebook metadata
# --------------------------------------------------
update_notebook_metadata() {
    UPDATE_METADATA_FILE="update_metadata.py"
    write_update_metadata_script "$UPDATE_METADATA_FILE"
    uv run python "$UPDATE_METADATA_FILE" "$NOTEBOOK" "$KERNEL_NAME" "$KERNEL_DISPLAY"
    rm -f "$UPDATE_METADATA_FILE"   
}

# --------------------------------------------------
# Launch Jupyter Lab
# --------------------------------------------------
launch_jupyter() {
    export JUPYTER_DISABLE_CONFIG=1
    log "🌐 Launching Jupyter Lab..."
    nohup uv run jupyter lab "$NOTEBOOK" >/dev/null 2>&1 &
    NEW_PID=$!
    echo "$NEW_PID" > "$PID_FILE"
    log "✅ Jupyter running (PID $NEW_PID)"
}
# --------------------------------------------------
# PYTHON SCRIPTS
# --------------------------------------------------

write_create_notebook_script() {
  local target="$1"
  cat > "$target" <<'PYCODE'
import sys
import nbformat

if len(sys.argv) < 3:
    print("Usage: python create_notebook.py <project_name> <notebook_filename>")
    sys.exit(1)

project_name = sys.argv[1]
notebook_filename = sys.argv[2]

nb = nbformat.v4.new_notebook(
    cells=[
        nbformat.v4.new_markdown_cell(
            f"# {project_name}\n\n"
            "This notebook was auto-generated by **launch_jupyter.command**.\n"
            "You can safely rename or delete it."
        )
    ],
    metadata={
        "kernelspec": {
            "name": "python3",
            "display_name": "Python 3",
            "language": "python"
        }
    }
)

with open(notebook_filename, "w", encoding="utf-8") as f:
    nbformat.write(nb, f)
print(f"Created {notebook_filename}")
PYCODE
}

write_update_metadata_script() {
  local target="$1"
  cat > "$target" <<'PYCODE'
import sys
import json

if len(sys.argv) < 4:
    print("Usage: python update_metadata.py <notebook_file> <kernel_name> <kernel_display>")
    sys.exit(1)

nb_file = sys.argv[1]
kernel_name = sys.argv[2]
kernel_display = sys.argv[3]

with open(nb_file, "r", encoding="utf-8") as f:
    nb = json.load(f)

nb['metadata']['kernelspec'] = {
    "name": kernel_name,
    "display_name": kernel_display,
    "language": "python"
}

with open(nb_file, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=2)

PYCODE
}
